run-switch: switch optimise garbage-collect-old

switch:
	home-manager switch --flake . --impure --extra-experimental-features 'nix-command flakes' --show-trace

build:
	home-manager build --flake . --impure --extra-experimental-features 'nix-command flakes' --show-trace

deploy-dry:
	nix run github:serokell/deploy-rs -- --dry-activate -- .#cake --impure --extra-experimental-features 'nix-command flakes' --show-trace

deploy-with-activate:
	mkdir -p ./logs
	nix run github:serokell/deploy-rs -- --log-dir ./logs -- .#cake --impure --extra-experimental-features 'nix-command flakes' --show-trace

deploy-dry-non-matching:
	nix run github:serokell/deploy-rs -- --skip-checks --dry-activate -- .#cake --impure --extra-experimental-features 'nix-command flakes' --show-trace

deploy-with-activate-non-matching:
	mkdir -p ./logs
	nix run github:serokell/deploy-rs -- --skip-checks --log-dir ./logs -- .#cake --impure --extra-experimental-features 'nix-command flakes' --show-trace


deploy: deploy-dry deploy-activate

switch-system:
	sudo nixos-rebuild switch --flake .#olivier --impure

build-system:
	sudo nixos-rebuild build --flake .#olivier --impure --show-trace

switch-darwin:
	sudo nix run nix-darwin -- switch --flake . --impure

build-darwin:
	nix run nix-darwin -- build --flake . --impure --show-trace

check:
	nix flake check

# TODO: Doesn't work when using Makefile, only manually.
hm-rollback:
	# When home-manager is not working try: `nix-shell -p home-manager`).
	bash $$(nix-shell -p home-manager generations | fzf | awk -F '-> ' '{print $2 "/activate"}')

garbage-collect-old:
	# Unlinks older profiles and then deletes unreachable store objects.
	nix-collect-garbage --delete-older-than 10d

garbage-collect:
	# Deletes unreachable store objects.
	nix-collect-garbage

list-old-profiles:
	# Includes gc roots generated by another programs like lorri or direnv.
	# Reference: https://www.reddit.com/r/NixOS/comments/1cunvdw/comment/l4jz8z1/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
	nix-store --gc --print-roots | grep -vE "^(/nix/var|/run/\w+-system|\{memory|/proc)" | awk '{ print $1 }' | grep -vE 'home-manager|flake-registry\.json'

garbage-collect-old-profiles:
	nix-store --gc --print-roots | grep -vE "^(/nix/var|/run/\w+-system|\{memory|/proc)" | awk '{ print $1 }' | grep -vE 'home-manager|flake-registry\.json' | xargs -L1 unlink

# Saves a little bit of space by hardlinking deps. Judging from logs,
# garbage-collect includes optimise.
optimise:
	nix-store --optimise

# When want to migrate to a newer version of nixpkgs and home-manager.
update:
	nix flake update

edit-vault:
	nix-shell -p sops --run "sops secrets/secrets.yaml"

# Edit in vault, change some content, save -> mac is updated.
# Use with care, only when you're sure you've just mistaken while
# resolving conflicts.
fix-vault-mac:
	nix-shell -p sops --run "sops --ignore-mac secrets/secrets.yaml"
