run-switch: switch optimise garbage-collect-old

init:
	git submodule update --init --recursive

switch:
	home-manager switch --flake . --impure --extra-experimental-features 'nix-command flakes' --show-trace

build:
	home-manager build --flake . --impure --extra-experimental-features 'nix-command flakes' --show-trace

deploy-dry:
	nix run github:serokell/deploy-rs -- --dry-activate -- .#cake --impure --extra-experimental-features 'nix-command flakes' --show-trace

deploy-with-activate:
	mkdir -p ./logs
	nix run github:serokell/deploy-rs -- --log-dir ./logs -- .#cake --impure --extra-experimental-features 'nix-command flakes' --show-trace

deploy-dry-non-matching:
	nix run github:serokell/deploy-rs -- --skip-checks --dry-activate -- .#cake --impure --extra-experimental-features 'nix-command flakes' --show-trace

deploy-with-activate-non-matching:
	mkdir -p ./logs
	nix run github:serokell/deploy-rs -- --skip-checks --log-dir ./logs -- .#cake --impure --extra-experimental-features 'nix-command flakes' --show-trace


deploy: deploy-dry deploy-activate

switch-system:
	sudo nixos-rebuild switch --flake .#olivier --impure

build-system:
	sudo nixos-rebuild build --flake .#olivier --impure --show-trace

switch-darwin:
	sudo nix run nix-darwin -- switch --flake . --impure

build-darwin:
	nix run nix-darwin -- build --flake . --impure --show-trace

check:
	nix flake check

# TODO: Doesn't work when using Makefile, only manually.
hm-rollback:
	# When home-manager is not working try: `nix-shell -p home-manager`).
	bash $$(nix-shell -p home-manager generations | fzf | awk -F '-> ' '{print $2 "/activate"}')

system-rollback:
	sudo nixos-rebuild switch --rollback

system-rollback-no-internet:
	sudo nixos-rebuild switch --rollback --no-net --offline --fast

garbage-collect-old:
	# Unlinks older profiles and then deletes unreachable store objects.
	nix-collect-garbage --delete-older-than 10d

garbage-collect:
	# Deletes unreachable store objects.
	nix-collect-garbage

list-old-profiles:
	# Includes gc roots generated by another programs like lorri or direnv.
	# Reference: https://www.reddit.com/r/NixOS/comments/1cunvdw/comment/l4jz8z1/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
	nix-store --gc --print-roots | grep -vE "^(/nix/var|/run/\w+-system|\{memory|/proc)" | awk '{ print $1 }' | grep -vE 'home-manager|flake-registry\.json'

garbage-collect-old-profiles:
	nix-store --gc --print-roots | grep -vE "^(/nix/var|/run/\w+-system|\{memory|/proc)" | awk '{ print $1 }' | grep -vE 'home-manager|flake-registry\.json' | xargs -L1 unlink

# Saves a little bit of space by hardlinking deps. Judging from logs,
# garbage-collect includes optimise.
optimise:
	nix-store --optimise

# When want to migrate to a newer version of nixpkgs and home-manager.
# Use `nix flake lock` if you just want to recreate lock file without updating
# any set versions.
update:
	nix flake update

edit-vault:
	nix-shell -p sops --run "sops secrets/secrets.yaml"

# Edit in vault, change some content, save -> mac is updated.
# Use with care, only when you're sure you've just mistaken while
# resolving conflicts.
fix-vault-mac:
	nix-shell -p sops --run "sops --ignore-mac secrets/secrets.yaml"
	# Not sure if it was needed: `nix-channel --update`

# StratoFrame % Virtual Machines
# # Qemu
build-vm-qemu:
	# Delete cached dynamic state of the virtual machine from previous build.
	rm --force nixos.qcow2
	nix-build '<nixpkgs/nixos>' -A vm -I nixpkgs=channel:nixos-24.11 -I nixos-config=./systems/x86_64-vm/simple/default.nix

start-vm-qemu-console:
	QEMU_KERNEL_PARAMS=console=ttyS0 ./result/bin/run-nixos-vm -nographic; reset

# Not recommended: qemu is quite slow when working with graphics.
start-vm-qemu:
	./result/bin/run-nixos-vm

# # VirtualBox
build-vm-vb:
	nix-build '<nixpkgs/nixos>' -A config.system.build.virtualBoxOVA -I nixpkgs=channel:nixos-24.11 -I nixos-config=./systems/x86_64-vm/vpn/default.nix

# # Docker
build-NikolaiGogol-hm:
	home-manager build --flake .#ds13@NikolaiGogol --impure --extra-experimental-features 'nix-command flakes' --show-trace

switch-NikolaiGogol-system:
	sudo nixos-rebuild switch --flake .#NikolaiGogol_inner --impure

build-NikolaiGogol-system:
	sudo nixos-rebuild build --flake .#NikolaiGogol_inner --impure --show-trace

build-NikolaiGogol:
	nix build --out-link result-NikolaiGogol .#dockerConfigurations.NikolaiGogol  --impure --extra-experimental-features 'nix-command flakes' --show-trace

