{
  config,
  lib,
  ...
}: let
  inherit (lib) hm mkIf;

  configDir = "${config.home.homeDirectory}/.config/opencode";

  # Files we want to de‑symlink (just the ones generated by the module).
  filesToMaterialise = [
    "opencode.json"
    "tui.json"
  ];
in
  {
    config = mkIf config.programs.opencode.enable {
      # Run *after* home‑manager has created all symlinks.
      home.activation.materialiseOpenCodeConfig = hm.dag.entryAfter ["writeBoundary"] (
        lib.concatMapStrings (fname: ''
          target="${configDir}/${fname}"
          # Only act if the file exists (module may have created a symlink)
          if [ -f "$target" ]; then
            # cp follows symlinks by default; it replaces the symlink with a regular file
            $DRY_RUN_CMD cp "$target" "$target.tmp" && $DRY_RUN_CMD mv "$target.tmp" "$target"
          fi
        '')
        filesToMaterialise
      );
    };
  }
