{
  config,
  lib,
  ...
}: let
  inherit (lib) hm mkIf;
  inherit (lib) baseNameOf;

  configDir = "${config.home.homeDirectory}/.config/opencode";
  skillsDir = "${configDir}/skill";
  agentsDir = "${configDir}/agent";

  inherit (config.programs.opencode) skillPaths;

  # Files we want to de‑symlink (just the ones generated by the module).
  filesToMaterialise = [
    "opencode.json"
    "tui.json"
  ];

  skillsToMaterialise = map baseNameOf skillPaths;
  agentsToMaterialise = lib.attrNames config.programs.opencode.agents;
in {
  config = mkIf config.programs.opencode.enable {
    # Run *after* home‑manager has created all symlinks.
    home.activation.materialiseOpenCodeConfig = hm.dag.entryAfter ["writeBoundary"] (
      # Config files
      lib.concatMapStrings (fname: ''
        target="${configDir}/${fname}"
        # Only act if the file exists (module may have created a symlink)
        if [ -f "$target" ]; then
          # cp follows symlinks by default; it replaces the symlink with a regular file
          $DRY_RUN_CMD cp "$target" "$target.tmp" && $DRY_RUN_CMD mv --force "$target.tmp" "$target"
        fi
      '') filesToMaterialise
      +
      # Skill directories
      lib.concatMapStrings (skillName: ''
        target="${skillsDir}/${skillName}"
        if [ -d "$target" ]; then
          tmp="${skillsDir}/.${skillName}.tmp"
          $DRY_RUN_CMD cp -rL "$target" "$tmp" && $DRY_RUN_CMD rm -rf -- "$target" && $DRY_RUN_CMD mv -- "$tmp" "$target"
        fi
      '') skillsToMaterialise
      +
      # Agent files
      lib.concatMapStrings (agentName: ''
        target="${agentsDir}/${agentName}.md"
        if [ -f "$target" ]; then
          tmp="${agentsDir}/.${agentName}.md.tmp"
          $DRY_RUN_CMD cp "$target" "$tmp" && $DRY_RUN_CMD mv --force "$tmp" "$target"
        fi
      '') agentsToMaterialise
    );
  };
}
